/**
 * SECTION 1: THE ASYNCHRONOUS COMPONENT INGESTION ENGINE
 * 
 * This function functions as a client-side layout compiler. It performs an asynchronous 
 * background HTTP network request to download a raw HTML component file (like a menu or footer) 
 * and injects it into a designated placeholder container on the active web page.
 * 
 * @param {string} elementId - The ID of the target HTML element container where the component will be injected.
 * @param {string} filePath  - The absolute web root file path location of the asset file (e.g., "/includes/menu.html").
 * @param {function} callback - [Optional] A function to execute immediately after the HTML finishes loading into the page.
 */
function loadComponent(elementId, filePath, callback = null) {
  // Trigger a modern, background asynchronous network request to fetch the static file
  fetch(filePath)
    .then(response => {
      // Defensive boundary check: If the file is missing (404) or restricted (403), throw an explicit error
      if (!response.ok) throw new Error(`Failed to load ${filePath}`);
      
      // If the request succeeds, extract and stream the raw file data content as a plain text string
      return response.text();
    })
    .then(data => {
      // Inject the downloaded plain-text HTML string directly into your target layout placeholder node
      document.getElementById(elementId).innerHTML = data;
      
      // Operational Hook: If a callback function was assigned during execution, run it right now
      if (callback) callback();
    })
    // Global safety catch: Logs network dropped connections or bad paths into the Console without crashing the website
    .catch(error => console.error(error));
}

/**
 * SECTION 2: THE ADAPTIVE PATH CALCULATION & HIGHLIGHT OPTIMIZATION
 * 
 * This function runs immediately after your menu.html component is loaded. It parses the browser's 
 * address bar, calculates exactly how many folder layers deep the visitor is resting from the root domain, 
 * overrides the blank '#' fallback links, and flags the active navigation menu item.
 */
function fixMenuPaths() {
  // Extract the active URL path (e.g., "/home-lab/guides/index.html") and split it open at every forward slash.
  // The .filter(Boolean) array loop scrubs out any double or empty trailing forward slash items.
  const path = window.location.pathname;
  const segments = path.split('/').filter(Boolean); 
  
  // Count the items inside the cleaned path array to measure folder nesting levels
  let depth = segments.length; 
  
  // Syntax edge-case fix: If the final array item ends explicitly in '.html' (meaning it is a file name node, 
  // not an organizational directory folder), subtract 1 from your depth calculations.
  if (segments.length > 0 && segments[segments.length - 1].endsWith('.html')) {
      depth = segments.length - 1;
  }
  
  // Conditional calculation layout: For every step down from the root, duplicate a directory-up path command ("../").
  // Depth 0 (Root) ➡️ "./"  |  Depth 1 (/home-lab/) ➡️ "../"  |  Depth 2 (/home-lab/guides/) ➡️ "../../"
  const rootPrefix = depth > 0 ? "../".repeat(depth) : "./"; 

  // Grab specific control hooks over the individual link anchor IDs generated by your menu component injection
  const navHome = document.getElementById('nav-home');
  const navGuides = document.getElementById('nav-guides');
  const navReference = document.getElementById('nav-reference');
  const navGateway = document.getElementById('nav-gateway');

  // Dynamic path rewriting array queue mapping
  if (navHome) navHome.href = rootPrefix + "index.html"; 
  if (navGuides) navGuides.href = rootPrefix + "guides/index.html"; 
  if (navReference) navReference.href = rootPrefix + "reference/index.html"; 
  if (navGateway) navGateway.href = rootPrefix + "index.html"; 

  // HIGHLIGHT LOGIC START: Collect all links inside your navigation container
  const navLinks = [navHome, navGuides, navReference, navGateway];

  navLinks.forEach(link => {
    if (!link) return; // Skip if the target element node wasn't found in memory

    // Convert the link's relative URL target string into a clean layout verification path array
    // (e.g., matching "../../guides/index.html" down to a normalized array mapping string evaluation)
    const linkPath = new URL(link.href, window.location.origin).pathname;
    const linkSegments = linkPath.split('/').filter(Boolean);
    
    // Evaluate structural folder layer matches
    let isMatch = false;

    if (linkSegments.length === 0 && segments.length === 0) {
      // Edge Case: Visitor is resting explicitly on the master root index.html domain dashboard page
      isMatch = true;
    } else if (linkSegments.length > 0 && segments.length > 0) {
      // General Folders: Match by primary structural category keyword identifier index string (e.g., 'guides')
      isMatch = linkSegments[0] === segments[0];
    }

    // If it is a structural validation match, inject an active modifier class into the element
    if (isMatch) {
      link.classList.add('active');
    }
  });
}

/**
 * SECTION 3: THE ASSEMBLY PIPELINE EXECUTION
 * 
 * This acts as the master ignition system. It waits until the core page structure has fully parsed in 
 * the browser, then fires off your background asset fetching script routines simultaneously.
 */
document.addEventListener("DOMContentLoaded", () => {
  // Ingest your global logo, tracking, and styling layout blocks
  loadComponent("header-placeholder", "/includes/header.html");
  
  // Critical Action: Ingest your navigation menu component, and pass 'fixMenuPaths' directly into 
  // the callback parameter loop so the URLs are re-mapped the exact millisecond the menu is built.
  loadComponent("menu-placeholder", "/includes/menu.html", fixMenuPaths);
  
  // Ingest your standardized footer copyright block
  loadComponent("footer-placeholder", "/includes/footer.html");
});
